// System
const RESET_INTERVAL = 300;
const CLOCK_INTERVAL = 1;
const CLOCK_INCREASING_FIX = 1.8;
const GRID_NUM_INIT = 9;
const ANT_NUM_INIT = 1;

// GRID Richness
const SUGAR_INIT = 256;
const SUGAR_RECOVERY_NUM = 4;

// ANT PARAM
const VIEW_WIDTH = 2;
const POOL_INIT = 4;
const TAKE_INIT = 6;
const APPETITE_INIT = 1;
const MOVE_RATE = 0.7;
const MOBILE_RATE = 0.2;

// Dead or Arrive
const BORN_LINE_OF_POOL = POOL_INIT * 100;
const DEATH_LINE_OF_POOL = 0;

export default {
  RESET_INTERVAL,
  CLOCK_INTERVAL,
  CLOCK_INCREASING_FIX,
  GRID_NUM_INIT,
  ANT_NUM_INIT,
  SUGAR_INIT,
  SUGAR_RECOVERY_NUM,
  VIEW_WIDTH,
  POOL_INIT,
  TAKE_INIT,
  APPETITE_INIT,
  MOVE_RATE,
  MOBILE_RATE,
  BORN_LINE_OF_POOL,
  DEATH_LINE_OF_POOL
};
